/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SchedulingRouteImport } from './routes/scheduling'
import { Route as RevenueRouteImport } from './routes/revenue'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as PharmacyRouteImport } from './routes/pharmacy'
import { Route as PatientsRouteImport } from './routes/patients'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FormBuilderRouteImport } from './routes/form-builder'
import { Route as ClinicalRouteImport } from './routes/clinical'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AccessDeniedRouteImport } from './routes/access-denied'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PatientsPatientIdRouteImport } from './routes/patients.$patientId'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SchedulingRoute = SchedulingRouteImport.update({
  id: '/scheduling',
  path: '/scheduling',
  getParentRoute: () => rootRouteImport,
} as any)
const RevenueRoute = RevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const PharmacyRoute = PharmacyRouteImport.update({
  id: '/pharmacy',
  path: '/pharmacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsRoute = PatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FormBuilderRoute = FormBuilderRouteImport.update({
  id: '/form-builder',
  path: '/form-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicalRoute = ClinicalRouteImport.update({
  id: '/clinical',
  path: '/clinical',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessDeniedRoute = AccessDeniedRouteImport.update({
  id: '/access-denied',
  path: '/access-denied',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsPatientIdRoute = PatientsPatientIdRouteImport.update({
  id: '/$patientId',
  path: '/$patientId',
  getParentRoute: () => PatientsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/access-denied': typeof AccessDeniedRoute
  '/analytics': typeof AnalyticsRoute
  '/clinical': typeof ClinicalRoute
  '/form-builder': typeof FormBuilderRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRoute
  '/patients': typeof PatientsRouteWithChildren
  '/pharmacy': typeof PharmacyRoute
  '/results': typeof ResultsRoute
  '/revenue': typeof RevenueRoute
  '/scheduling': typeof SchedulingRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/patients/$patientId': typeof PatientsPatientIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/access-denied': typeof AccessDeniedRoute
  '/analytics': typeof AnalyticsRoute
  '/clinical': typeof ClinicalRoute
  '/form-builder': typeof FormBuilderRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRoute
  '/patients': typeof PatientsRouteWithChildren
  '/pharmacy': typeof PharmacyRoute
  '/results': typeof ResultsRoute
  '/revenue': typeof RevenueRoute
  '/scheduling': typeof SchedulingRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/patients/$patientId': typeof PatientsPatientIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/access-denied': typeof AccessDeniedRoute
  '/analytics': typeof AnalyticsRoute
  '/clinical': typeof ClinicalRoute
  '/form-builder': typeof FormBuilderRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRoute
  '/patients': typeof PatientsRouteWithChildren
  '/pharmacy': typeof PharmacyRoute
  '/results': typeof ResultsRoute
  '/revenue': typeof RevenueRoute
  '/scheduling': typeof SchedulingRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/patients/$patientId': typeof PatientsPatientIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access-denied'
    | '/analytics'
    | '/clinical'
    | '/form-builder'
    | '/login'
    | '/orders'
    | '/patients'
    | '/pharmacy'
    | '/results'
    | '/revenue'
    | '/scheduling'
    | '/settings'
    | '/setup'
    | '/patients/$patientId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/access-denied'
    | '/analytics'
    | '/clinical'
    | '/form-builder'
    | '/login'
    | '/orders'
    | '/patients'
    | '/pharmacy'
    | '/results'
    | '/revenue'
    | '/scheduling'
    | '/settings'
    | '/setup'
    | '/patients/$patientId'
  id:
    | '__root__'
    | '/'
    | '/access-denied'
    | '/analytics'
    | '/clinical'
    | '/form-builder'
    | '/login'
    | '/orders'
    | '/patients'
    | '/pharmacy'
    | '/results'
    | '/revenue'
    | '/scheduling'
    | '/settings'
    | '/setup'
    | '/patients/$patientId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessDeniedRoute: typeof AccessDeniedRoute
  AnalyticsRoute: typeof AnalyticsRoute
  ClinicalRoute: typeof ClinicalRoute
  FormBuilderRoute: typeof FormBuilderRoute
  LoginRoute: typeof LoginRoute
  OrdersRoute: typeof OrdersRoute
  PatientsRoute: typeof PatientsRouteWithChildren
  PharmacyRoute: typeof PharmacyRoute
  ResultsRoute: typeof ResultsRoute
  RevenueRoute: typeof RevenueRoute
  SchedulingRoute: typeof SchedulingRoute
  SettingsRoute: typeof SettingsRoute
  SetupRoute: typeof SetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scheduling': {
      id: '/scheduling'
      path: '/scheduling'
      fullPath: '/scheduling'
      preLoaderRoute: typeof SchedulingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revenue': {
      id: '/revenue'
      path: '/revenue'
      fullPath: '/revenue'
      preLoaderRoute: typeof RevenueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pharmacy': {
      id: '/pharmacy'
      path: '/pharmacy'
      fullPath: '/pharmacy'
      preLoaderRoute: typeof PharmacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients': {
      id: '/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof PatientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/form-builder': {
      id: '/form-builder'
      path: '/form-builder'
      fullPath: '/form-builder'
      preLoaderRoute: typeof FormBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinical': {
      id: '/clinical'
      path: '/clinical'
      fullPath: '/clinical'
      preLoaderRoute: typeof ClinicalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access-denied': {
      id: '/access-denied'
      path: '/access-denied'
      fullPath: '/access-denied'
      preLoaderRoute: typeof AccessDeniedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/$patientId': {
      id: '/patients/$patientId'
      path: '/$patientId'
      fullPath: '/patients/$patientId'
      preLoaderRoute: typeof PatientsPatientIdRouteImport
      parentRoute: typeof PatientsRoute
    }
  }
}

interface PatientsRouteChildren {
  PatientsPatientIdRoute: typeof PatientsPatientIdRoute
}

const PatientsRouteChildren: PatientsRouteChildren = {
  PatientsPatientIdRoute: PatientsPatientIdRoute,
}

const PatientsRouteWithChildren = PatientsRoute._addFileChildren(
  PatientsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessDeniedRoute: AccessDeniedRoute,
  AnalyticsRoute: AnalyticsRoute,
  ClinicalRoute: ClinicalRoute,
  FormBuilderRoute: FormBuilderRoute,
  LoginRoute: LoginRoute,
  OrdersRoute: OrdersRoute,
  PatientsRoute: PatientsRouteWithChildren,
  PharmacyRoute: PharmacyRoute,
  ResultsRoute: ResultsRoute,
  RevenueRoute: RevenueRoute,
  SchedulingRoute: SchedulingRoute,
  SettingsRoute: SettingsRoute,
  SetupRoute: SetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
