/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkflowsRouteImport } from './routes/workflows'
import { Route as WardsRouteImport } from './routes/wards'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SchedulingRouteImport } from './routes/scheduling'
import { Route as RevenueRouteImport } from './routes/revenue'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as RadiologyRouteImport } from './routes/radiology'
import { Route as PhysicsDemoRouteImport } from './routes/physics-demo'
import { Route as PharmacyRouteImport } from './routes/pharmacy'
import { Route as PatientsRouteImport } from './routes/patients'
import { Route as OtRouteImport } from './routes/ot'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as OpdRouteImport } from './routes/opd'
import { Route as MyTrainingRouteImport } from './routes/my-training'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LabRouteImport } from './routes/lab'
import { Route as IpdRouteImport } from './routes/ipd'
import { Route as FormBuilderRouteImport } from './routes/form-builder'
import { Route as ComplianceStatusRouteImport } from './routes/compliance-status'
import { Route as ClinicalRouteImport } from './routes/clinical'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as BedsRouteImport } from './routes/beds'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AccessDeniedRouteImport } from './routes/access-denied'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PatientsPatientIdRouteImport } from './routes/patients.$patientId'

const WorkflowsRoute = WorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => rootRouteImport,
} as any)
const WardsRoute = WardsRouteImport.update({
  id: '/wards',
  path: '/wards',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SchedulingRoute = SchedulingRouteImport.update({
  id: '/scheduling',
  path: '/scheduling',
  getParentRoute: () => rootRouteImport,
} as any)
const RevenueRoute = RevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const RadiologyRoute = RadiologyRouteImport.update({
  id: '/radiology',
  path: '/radiology',
  getParentRoute: () => rootRouteImport,
} as any)
const PhysicsDemoRoute = PhysicsDemoRouteImport.update({
  id: '/physics-demo',
  path: '/physics-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const PharmacyRoute = PharmacyRouteImport.update({
  id: '/pharmacy',
  path: '/pharmacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsRoute = PatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => rootRouteImport,
} as any)
const OtRoute = OtRouteImport.update({
  id: '/ot',
  path: '/ot',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const OpdRoute = OpdRouteImport.update({
  id: '/opd',
  path: '/opd',
  getParentRoute: () => rootRouteImport,
} as any)
const MyTrainingRoute = MyTrainingRouteImport.update({
  id: '/my-training',
  path: '/my-training',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LabRoute = LabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => rootRouteImport,
} as any)
const IpdRoute = IpdRouteImport.update({
  id: '/ipd',
  path: '/ipd',
  getParentRoute: () => rootRouteImport,
} as any)
const FormBuilderRoute = FormBuilderRouteImport.update({
  id: '/form-builder',
  path: '/form-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceStatusRoute = ComplianceStatusRouteImport.update({
  id: '/compliance-status',
  path: '/compliance-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicalRoute = ClinicalRouteImport.update({
  id: '/clinical',
  path: '/clinical',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const BedsRoute = BedsRouteImport.update({
  id: '/beds',
  path: '/beds',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessDeniedRoute = AccessDeniedRouteImport.update({
  id: '/access-denied',
  path: '/access-denied',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsPatientIdRoute = PatientsPatientIdRouteImport.update({
  id: '/$patientId',
  path: '/$patientId',
  getParentRoute: () => PatientsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/access-denied': typeof AccessDeniedRoute
  '/analytics': typeof AnalyticsRoute
  '/beds': typeof BedsRoute
  '/billing': typeof BillingRoute
  '/clinical': typeof ClinicalRoute
  '/compliance-status': typeof ComplianceStatusRoute
  '/form-builder': typeof FormBuilderRoute
  '/ipd': typeof IpdRoute
  '/lab': typeof LabRoute
  '/login': typeof LoginRoute
  '/my-training': typeof MyTrainingRoute
  '/opd': typeof OpdRoute
  '/orders': typeof OrdersRoute
  '/ot': typeof OtRoute
  '/patients': typeof PatientsRouteWithChildren
  '/pharmacy': typeof PharmacyRoute
  '/physics-demo': typeof PhysicsDemoRoute
  '/radiology': typeof RadiologyRoute
  '/results': typeof ResultsRoute
  '/revenue': typeof RevenueRoute
  '/scheduling': typeof SchedulingRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/wards': typeof WardsRoute
  '/workflows': typeof WorkflowsRoute
  '/patients/$patientId': typeof PatientsPatientIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/access-denied': typeof AccessDeniedRoute
  '/analytics': typeof AnalyticsRoute
  '/beds': typeof BedsRoute
  '/billing': typeof BillingRoute
  '/clinical': typeof ClinicalRoute
  '/compliance-status': typeof ComplianceStatusRoute
  '/form-builder': typeof FormBuilderRoute
  '/ipd': typeof IpdRoute
  '/lab': typeof LabRoute
  '/login': typeof LoginRoute
  '/my-training': typeof MyTrainingRoute
  '/opd': typeof OpdRoute
  '/orders': typeof OrdersRoute
  '/ot': typeof OtRoute
  '/patients': typeof PatientsRouteWithChildren
  '/pharmacy': typeof PharmacyRoute
  '/physics-demo': typeof PhysicsDemoRoute
  '/radiology': typeof RadiologyRoute
  '/results': typeof ResultsRoute
  '/revenue': typeof RevenueRoute
  '/scheduling': typeof SchedulingRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/wards': typeof WardsRoute
  '/workflows': typeof WorkflowsRoute
  '/patients/$patientId': typeof PatientsPatientIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/access-denied': typeof AccessDeniedRoute
  '/analytics': typeof AnalyticsRoute
  '/beds': typeof BedsRoute
  '/billing': typeof BillingRoute
  '/clinical': typeof ClinicalRoute
  '/compliance-status': typeof ComplianceStatusRoute
  '/form-builder': typeof FormBuilderRoute
  '/ipd': typeof IpdRoute
  '/lab': typeof LabRoute
  '/login': typeof LoginRoute
  '/my-training': typeof MyTrainingRoute
  '/opd': typeof OpdRoute
  '/orders': typeof OrdersRoute
  '/ot': typeof OtRoute
  '/patients': typeof PatientsRouteWithChildren
  '/pharmacy': typeof PharmacyRoute
  '/physics-demo': typeof PhysicsDemoRoute
  '/radiology': typeof RadiologyRoute
  '/results': typeof ResultsRoute
  '/revenue': typeof RevenueRoute
  '/scheduling': typeof SchedulingRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/wards': typeof WardsRoute
  '/workflows': typeof WorkflowsRoute
  '/patients/$patientId': typeof PatientsPatientIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access-denied'
    | '/analytics'
    | '/beds'
    | '/billing'
    | '/clinical'
    | '/compliance-status'
    | '/form-builder'
    | '/ipd'
    | '/lab'
    | '/login'
    | '/my-training'
    | '/opd'
    | '/orders'
    | '/ot'
    | '/patients'
    | '/pharmacy'
    | '/physics-demo'
    | '/radiology'
    | '/results'
    | '/revenue'
    | '/scheduling'
    | '/settings'
    | '/setup'
    | '/wards'
    | '/workflows'
    | '/patients/$patientId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/access-denied'
    | '/analytics'
    | '/beds'
    | '/billing'
    | '/clinical'
    | '/compliance-status'
    | '/form-builder'
    | '/ipd'
    | '/lab'
    | '/login'
    | '/my-training'
    | '/opd'
    | '/orders'
    | '/ot'
    | '/patients'
    | '/pharmacy'
    | '/physics-demo'
    | '/radiology'
    | '/results'
    | '/revenue'
    | '/scheduling'
    | '/settings'
    | '/setup'
    | '/wards'
    | '/workflows'
    | '/patients/$patientId'
  id:
    | '__root__'
    | '/'
    | '/access-denied'
    | '/analytics'
    | '/beds'
    | '/billing'
    | '/clinical'
    | '/compliance-status'
    | '/form-builder'
    | '/ipd'
    | '/lab'
    | '/login'
    | '/my-training'
    | '/opd'
    | '/orders'
    | '/ot'
    | '/patients'
    | '/pharmacy'
    | '/physics-demo'
    | '/radiology'
    | '/results'
    | '/revenue'
    | '/scheduling'
    | '/settings'
    | '/setup'
    | '/wards'
    | '/workflows'
    | '/patients/$patientId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessDeniedRoute: typeof AccessDeniedRoute
  AnalyticsRoute: typeof AnalyticsRoute
  BedsRoute: typeof BedsRoute
  BillingRoute: typeof BillingRoute
  ClinicalRoute: typeof ClinicalRoute
  ComplianceStatusRoute: typeof ComplianceStatusRoute
  FormBuilderRoute: typeof FormBuilderRoute
  IpdRoute: typeof IpdRoute
  LabRoute: typeof LabRoute
  LoginRoute: typeof LoginRoute
  MyTrainingRoute: typeof MyTrainingRoute
  OpdRoute: typeof OpdRoute
  OrdersRoute: typeof OrdersRoute
  OtRoute: typeof OtRoute
  PatientsRoute: typeof PatientsRouteWithChildren
  PharmacyRoute: typeof PharmacyRoute
  PhysicsDemoRoute: typeof PhysicsDemoRoute
  RadiologyRoute: typeof RadiologyRoute
  ResultsRoute: typeof ResultsRoute
  RevenueRoute: typeof RevenueRoute
  SchedulingRoute: typeof SchedulingRoute
  SettingsRoute: typeof SettingsRoute
  SetupRoute: typeof SetupRoute
  WardsRoute: typeof WardsRoute
  WorkflowsRoute: typeof WorkflowsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workflows': {
      id: '/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof WorkflowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wards': {
      id: '/wards'
      path: '/wards'
      fullPath: '/wards'
      preLoaderRoute: typeof WardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scheduling': {
      id: '/scheduling'
      path: '/scheduling'
      fullPath: '/scheduling'
      preLoaderRoute: typeof SchedulingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revenue': {
      id: '/revenue'
      path: '/revenue'
      fullPath: '/revenue'
      preLoaderRoute: typeof RevenueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/radiology': {
      id: '/radiology'
      path: '/radiology'
      fullPath: '/radiology'
      preLoaderRoute: typeof RadiologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/physics-demo': {
      id: '/physics-demo'
      path: '/physics-demo'
      fullPath: '/physics-demo'
      preLoaderRoute: typeof PhysicsDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pharmacy': {
      id: '/pharmacy'
      path: '/pharmacy'
      fullPath: '/pharmacy'
      preLoaderRoute: typeof PharmacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients': {
      id: '/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof PatientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ot': {
      id: '/ot'
      path: '/ot'
      fullPath: '/ot'
      preLoaderRoute: typeof OtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opd': {
      id: '/opd'
      path: '/opd'
      fullPath: '/opd'
      preLoaderRoute: typeof OpdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-training': {
      id: '/my-training'
      path: '/my-training'
      fullPath: '/my-training'
      preLoaderRoute: typeof MyTrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab': {
      id: '/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof LabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ipd': {
      id: '/ipd'
      path: '/ipd'
      fullPath: '/ipd'
      preLoaderRoute: typeof IpdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/form-builder': {
      id: '/form-builder'
      path: '/form-builder'
      fullPath: '/form-builder'
      preLoaderRoute: typeof FormBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance-status': {
      id: '/compliance-status'
      path: '/compliance-status'
      fullPath: '/compliance-status'
      preLoaderRoute: typeof ComplianceStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinical': {
      id: '/clinical'
      path: '/clinical'
      fullPath: '/clinical'
      preLoaderRoute: typeof ClinicalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beds': {
      id: '/beds'
      path: '/beds'
      fullPath: '/beds'
      preLoaderRoute: typeof BedsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access-denied': {
      id: '/access-denied'
      path: '/access-denied'
      fullPath: '/access-denied'
      preLoaderRoute: typeof AccessDeniedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/$patientId': {
      id: '/patients/$patientId'
      path: '/$patientId'
      fullPath: '/patients/$patientId'
      preLoaderRoute: typeof PatientsPatientIdRouteImport
      parentRoute: typeof PatientsRoute
    }
  }
}

interface PatientsRouteChildren {
  PatientsPatientIdRoute: typeof PatientsPatientIdRoute
}

const PatientsRouteChildren: PatientsRouteChildren = {
  PatientsPatientIdRoute: PatientsPatientIdRoute,
}

const PatientsRouteWithChildren = PatientsRoute._addFileChildren(
  PatientsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessDeniedRoute: AccessDeniedRoute,
  AnalyticsRoute: AnalyticsRoute,
  BedsRoute: BedsRoute,
  BillingRoute: BillingRoute,
  ClinicalRoute: ClinicalRoute,
  ComplianceStatusRoute: ComplianceStatusRoute,
  FormBuilderRoute: FormBuilderRoute,
  IpdRoute: IpdRoute,
  LabRoute: LabRoute,
  LoginRoute: LoginRoute,
  MyTrainingRoute: MyTrainingRoute,
  OpdRoute: OpdRoute,
  OrdersRoute: OrdersRoute,
  OtRoute: OtRoute,
  PatientsRoute: PatientsRouteWithChildren,
  PharmacyRoute: PharmacyRoute,
  PhysicsDemoRoute: PhysicsDemoRoute,
  RadiologyRoute: RadiologyRoute,
  ResultsRoute: ResultsRoute,
  RevenueRoute: RevenueRoute,
  SchedulingRoute: SchedulingRoute,
  SettingsRoute: SettingsRoute,
  SetupRoute: SetupRoute,
  WardsRoute: WardsRoute,
  WorkflowsRoute: WorkflowsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
